* SRFI Metadata
This repository contains a collection of parseable [[https://srfi.schemers.org][SRFI]] metadata.
Contributions welcome!

You can view the table [[http://htmlpreview.github.io/?https://github.com/schemedoc/srfi-metadata/blob/master/table.html][here]].

** How to update the table

   Simply run =generate.sh=, which takes the following steps:

   * Runs =srfi-data.sh= to refresh =data/srfi-data.scm=.

   * Runs =listings.sh= to generate the scripts in =listings/*.sh= and
   run them to obtain each implementation's list of supported SRFIs.

   * Runs =external.sh= to obtain SRFI support data for implementations'
   external libraries.

   * Runs =table.sh= to generate =table.html= and open it.

   Once =table.html= has been generated, it is committed to git.

   Run =upload.sh= to publish it to the web server.

** Requirements

  =listings.sh= calls Gauche by default, but you can adjust it to use
  any R7RS Scheme.

  =external.sh= and =table.sh= need Racket and =raco pkg install sxml=
