#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
curl --fail --silent --show-error --location \
	https://github.com/manuel-serrano/bigloo/archive/4.3h.tar.gz |
	gunzip |
	tar -xf - --to-stdout --wildcards 'bigloo-4.3h/manuals/srfi.texi' |
	grep -oE '^@item @code{srfi-[0-9]+} ' |
	grep -oE '[0-9]+' |
	sort -g |
	uniq > ../data/bigloo.scm
