#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
curl --fail --silent --show-error --location \
	https://github.com/ashinn/chibi-scheme/archive/master.tar.gz |
	gunzip |
	${TAR:-tar} -tf - |
	grep -oE 'chibi-scheme-master/lib/srfi/[0-9]+.sld' |
	sed 's@%3a@@' |
	grep -oE '[0-9]+' |
	sort -g |
	uniq > ../data/chibi-head.scm
