#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
curl --fail --silent --show-error --location \
	https://github.com/gambit/gambit/archive/v4.9.3.tar.gz |
	gunzip |
	tar -tf - |
	grep -oE 'gambit-4.9.3/lib/srfi/[0-9]+' |
	sed 's@%3a@@' |
	grep -oE '[0-9]+' |
	sort -g |
	uniq > ../data/gambit.scm
