#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
{
    curl --location --fail --silent --show-error \
        https://github.com/shirok/Gauche/archive/master.tar.gz |
        gunzip |
        ${TAR:-tar} -xf - --to-stdout --wildcards 'Gauche-master/src/srfis.scm' |
        grep -oE '^srfi-[0-9]+'
} | grep -oE '[0-9]+' | sort -g | uniq >../data/gauche-head.scm
