#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
curl --fail --silent --show-error --location \
	https://github.com/vyzo/gerbil/archive/v0.16.tar.gz |
	gunzip |
	${TAR:-tar} -xf - --to-stdout --wildcards 'gerbil-0.16/doc/guide/srfi.md' |
	grep -oE '\[SRFI +[0-9]+\]' |
	grep -oE '[0-9]+' |
	sort -g |
	uniq > ../data/gerbil.scm
