#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
{
    curl --location --fail --silent --show-error \
        https://github.com/racket/srfi/archive/v8.2.tar.gz |
        gunzip |
        ${TAR:-tar} -tf - |
        sed 's@[^/]*/@@' |
        grep -oE 'srfi-lib/srfi/[%a0-9]*' |
        sed 's@%3a@@'
} | grep -oE '[0-9]+' | sort -g | uniq >../data/racket.scm
