#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
{
    curl --location --fail --silent --show-error \
        https://github.com/racket/srfi/archive/master.tar.gz |
        gunzip |
        ${TAR:-tar} -tf - |
        grep -oE 'srfi-master/srfi-lib/srfi/%3a[0-9]+.rkt' |
        sed 's@[^/]*/@@' |
        sed 's@%3a@@'
} | grep -oE '[0-9]+' | sort -g | uniq >../data/racket-head.scm
