#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
{
    curl --location --fail --silent --show-error \
        https://github.com/ktakashi/sagittarius-scheme/archive/version_0.9.11.tar.gz |
        gunzip |
        ${TAR:-tar} -xf - --to-stdout --wildcards 'sagittarius-scheme-version_0.9.11/doc/srfi.md' |
        grep -oE 'SRFI-[0-9]+]'
} | grep -oE '[0-9]+' | sort -g | uniq >../data/sagittarius.scm
