#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
curl --fail --silent --show-error --location \
	https://github.com/egallesio/STklos/archive/master.tar.gz |
	gunzip |
	${TAR:-tar} -xf - --to-stdout --wildcards 'STklos-master/doc/skb/srfi.stk' |
	grep -oE '^ +.?\(?\([0-9]+ +\. "' |
	grep -oE '[0-9]+' |
	sort -g |
	uniq > ../data/stklos-head.scm
