#!/bin/bash
# Auto-generated by listings.scm
set -eu -o pipefail
cd "$(dirname "$0")"
curl --fail --silent --show-error --location \
	https://gitlab.com/nieper/unsyntax/-/archive/v0.0.3/unsyntax-v0.0.3.tar.gz |
	gunzip |
	tar -tf - |
	grep -oE 'unsyntax-v0.0.3.*/src/srfi/[0-9]+.s.?.?' |
	sed 's@%3a@@' |
	grep -oE '[0-9]+' |
	sort -g |
	uniq > ../data/unsyntax.scm
